name: gcc
favicon: null
layout_spectrum: 0.9902257272042334
typography_spectrum: 0.9254650867078453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.330928020644933
  lightness: 0.6945900390855968
  saturation: 0.36985493963584304
  rhythmicContrast: 0.4518912087660283
purpose: []
